version = 1

test_patterns = ["__tests__/**"]

exclude_patterns = [
  "lib/**",
  "dist/**"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jest"]