name: Publish to NPM
on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 10

      - name: Use Node.js 22
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.x
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm publish --access public --no-git-checks

      - name: Build Package
        id: build-package
        run: |
          pnpm pack
          # Add the built package to the step outputs for later use
          echo "PACKAGE_PATH=$(find . -name "*.tgz" -print -quit)" >> $GITHUB_OUTPUT

      - name: Upload to S3
        run: |
          aws s3 cp ${{ steps.build-package.outputs.PACKAGE_PATH }} s3://github-actions-artifacts/npm-builds/workers-common/${{ steps.build-package.outputs.PACKAGE_PATH }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: https://8be772befd147a8df540aae0fa15c047.r2.cloudflarestorage.com

      - name: Add step summary with artifact link
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        env:
          ARTIFACT_URL: ${{ vars.ARTIFACT_PUBLIC_DOMAIN_BARE }}/npm-builds/
        with:
          script: |
            const artifactUrl = process.env.ARTIFACT_URL + 'workers-common/${{ steps.build-package.outputs.PACKAGE_PATH }}';
            const summaryBody = `Built package has been uploaded to S3. You can download it from the link below.`;
            core.summary.addHeading('Snapshot Release').addRaw(summaryBody).addBreak().addLink('Download Artifacts', artifactUrl).write();